# Generated by Django 6.0.6 on 2026-09-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sellerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='country',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='state_province',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='street_address',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
