# Generated by Django 6.0.6 on 2026-09-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_sellerprofile_country_sellerprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='avatar_url',
            field=models.TextField(blank=True),
        ),
    ]
