# Generated by Django 6.0.6 on 2026-08-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
