# Generated by Django 6.0.6 on 2026-09-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_is_promoted_car_promoted_at_savedsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_available_for_rent',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='minimum_rent_days',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='car',
            name='rent_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='rent_price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='rent_price_per_week',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
