# Generated by Django 6.0.6 on 2026-09-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_car_is_available_for_rent_car_minimum_rent_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='car',
            name='condition',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='car',
            name='image_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='image_url',
            field=models.TextField(),
        ),
    ]
